version: "3"

services:
  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=checkpoint
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
